services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-json-timer
    ports:
      - "6378:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  app:
    build: .
    container_name: timer-app
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6378
      - BASE_URL=http://localhost:5001
    volumes:
      - .:/app
